[package]
name = "keyvibe"
version = "0.1.0"
edition = "2024"

[dependencies]
cpal = "0.16.0"
evdev = "0.13.1"
rodio = "0.21.1"
serde = { version = "1.0.219", features = ["derive"] }
shellexpand = "3.1.1"
toml = "0.9.2"
